# eve-gateway
[routes."auth"]
service_url = "https://localhost:9998"

# industry
[routes."eve-gateway"]
service_url = "https://localhost:9998"

# industry
[routes."industry"]
service_url = "https://localhost:9994"

# industry
[routes."structure"]
service_url = "https://localhost:9994"

# store
[routes."store"]
service_url = "https://localhost:9996"

