# eve-gateway
[routes."auth"]
service_url = "https://localhost:9998"

# eve-gateway
[routes."eve"]
service_url = "https://localhost:9998"
drop_prefix = true

# industry
[routes."project-groups"]
service_url = "https://localhost:9994"

# industry
[routes."structures"]
service_url = "https://localhost:9994"

# industry
[routes."structure-groups"]
service_url = "https://localhost:9994"

# store
[routes."products"]
service_url = "https://localhost:9996"

[routes."orders"]
service_url = "https://localhost:9996"

[routes."admin"]
service_url = "https://localhost:9996"

[routes."general"]
service_url = "https://localhost:9996"
require_auth = false
