[domains."industry.dev.starfoundry.space"]
admins = [
    2117441999,
]
whitelist = [
    2117441999,
]
character_scopes = [
    "publicData",
    "esi-universe.read_structures.v1",
    "esi-markets.structure_markets.v1",
    "esi-skills.read_skills.v1",
    "esi-characters.read_blueprints.v1",
    "esi-assets.read_assets.v1",
    "esi-industry.read_character_jobs.v1",
]
corporation_scopes = [
    "esi-corporations.read_blueprints.v1",
    "esi-assets.read_corporation_assets.v1",
    "esi-industry.read_corporation_jobs.v1",
]
redirect = "https://industry.dev.starfoundry.space/api/auth/callback"

[domains."store.dev.starfoundry.space"]
admins = [
    2117441999,
]
whitelist = [
    99010079,
]
character_scopes = [
    "publicData",
]
corporation_scopes = []
redirect = "https://store.dev.starfoundry.space/api/auth/callback"
