name: rust-tests

on:
  workflow_call:
    inputs:
      folder:
        description: 'Folder to a rust project that should be tested'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  check:
    name: check
    runs-on:
      - self-hosted
      - linux
    steps:
      - uses: actions/checkout@master
      - name: cargo check
        env:
          SQLX_OFFLINE: true
        run: |
          cd ${{ inputs.folder }}
          cargo check

  test:
    name: tests
    runs-on:
      - self-hosted
      - linux
    needs:
      - check
    services:
      postgres:
        image: postgres:18
        ports:
          - 5678:5432
        options: >-
          -e POSTGRES_PASSWORD=postgres
          -e POSTGRES_DB=for-testing
          -v /tmp/github_postgres_testing/${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}:/var/lib/postgresql
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@master
      - name: cargo test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5678/for-testing
          STARFOUNDRY_STORE_DATABASE_URL: postgresql://postgres:postgres@localhost:5678/for-testing
          STARFOUNDRY_INDUSTRY_DATABASE_URL: postgresql://postgres:postgres@localhost:5678/for-testing
        run: |
          cd ${{ inputs.folder }}
          sqlx migrate run || true
          cargo test
