name: store-webapp

on:
  push:
    branches:
      - main
      - rewrite
    paths:
      - 'store_webapp/**'
      - '.github/workflows/trigger_store-webapp.yml'
      - 'Dockerfile'

concurrency:
  # Make sure every job on main has unique group id (run_id), so cancel-in-progress only affects PR's
  # https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout
  packages: write # for ghcr.io

jobs:
  test:
    uses: ./.github/workflows/common_webapp_test.yml
    secrets: inherit
    with:
      folder: store_webapp

  build-image:
    uses: ./.github/workflows/common_build_docker.yml
    secrets: inherit
    needs:
      - test
    with:
      name: store/webapp
      image: store-webapp

  ship-id:
    uses: ./.github/workflows/common_deploy.yml
    needs:
      - build-image
    secrets: inherit
    with:
      image: ${{ needs.build-image.outputs.IMAGE }}
      image-name: store-webapp
      folder: store
