name: market_worker

on:
  push:
    branches:
      - main
      - rewrite
    paths:
      - 'market_worker/**'
      - 'market_lib/**'
      - 'gateway_lib/**'
      - 'gp_lib-types/**'
      - 'worker_lib/**'
      - '.github/workflows/trigger_market_worker.yml'
      - 'Dockerfile'

concurrency:
  # Make sure every job on main has unique group id (run_id), so cancel-in-progress only affects PR's
  # https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout
  packages: write # for ghcr.io

jobs:
  test:
    uses: ./.github/workflows/common_rust_test.yml
    secrets: inherit
    with:
      folder: market_worker

  build-image:
    uses: ./.github/workflows/common_build_docker.yml
    secrets: inherit
    needs:
      - test
    with:
      name: market/worker
      image: market-worker

  ship-it:
    uses: ./.github/workflows/common_deploy.yml
    needs:
      - build-image
    secrets: inherit
    with:
      image: ${{ needs.build-image.outputs.IMAGE }}
      image-name: market-worker
      folder: market
