name: industry-hubs-webapp

on:
  push:
    branches:
      - main
      - rewrite
    paths:
      - 'industry-hub_webapp/**'
      - '.github/workflows/trigger_industry_hub-webapp.yml'
      - 'Dockerfile'

concurrency:
  # Make sure every job on main has unique group id (run_id), so cancel-in-progress only affects PR's
  # https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout
  packages: write # for ghcr.io

jobs:
  #test:
  #  uses: ./.github/workflows/common_webapp_test.yml
  #  secrets: inherit
  #  with:
  #    folder: webapp_industry

  build-image:
    uses: ./.github/workflows/common_build_docker.yml
    secrets: inherit
    #needs:
    #  - test
    with:
      name: industry-hub/webapp
      image: industry-hub-webapp

  ship-id:
    uses: ./.github/workflows/common_deploy.yml
    needs:
      - build-image
    secrets: inherit
    with:
      image: ${{ needs.build-image.outputs.IMAGE }}
      image-name: industry-hub-webapp
      folder: industry-hub
