name: store-api

on:
  push:
    branches:
      - main
      - rewrite
    paths:
      - 'store/**'
      - 'eve-gateway_lib/**'
      - '.github/workflows/trigger_store-api.yml'

concurrency:
  # Make sure every job on main has unique group id (run_id), so cancel-in-progress only affects PR's
  # https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  test:
    uses: ./.github/workflows/common_rust_test.yml
    secrets: inherit
    with:
      folder: store

  build-image:
    uses: ./.github/workflows/common_build_docker.yml
    secrets: inherit
    needs:
      - test
    with:
      name: store/api
      image: store-api

  ship-it:
    uses: ./.github/workflows/common_deploy.yml
    needs:
      - build-image
    secrets: inherit
    with:
      image: ${{ needs.build-image.outputs.IMAGE }}
      image-name: store-api
      folder: store
